### ISSUE TITLE
error while evaluating conditional ("prometheus" in prometheus_components): 'prometheus_components' is undefined

### ISSUE THREAD

**Issue by patsevanton** [buluma/ansible-role-prometheus#5]
## Describe the bug

error while evaluating conditional ("prometheus" in prometheus_components): 'prometheus_components' is undefined

## Playbook

```yaml
---
- name: Install prometheus and Grafana
  hosts: prometheus
  roles:
    - role: cloudalchemy.node_exporter
    - role: cloudalchemy.prometheus
      vars:
        prometheus_targets:
          node:
          - targets:
            - localhost:9100
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: enter_your_secure_password
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://localhost:9090'
            basicAuth: false
        dashboards:
        - dashboard_id: 1860
          revision_id: 26
          datasource: prometheus
```

## Output

```
TASK [buluma.prometheus : set internal variables for convenience] ************************************************************************************************************************
Tuesday 29 March 2022  14:27:48 +0600 (0:00:00.012)       0:00:26.259 *********
fatal: [prometheus]: FAILED! =>
  msg: |-
    The conditional check '"prometheus" in prometheus_components' failed. The error was: error while evaluating conditional ("prometheus" in prometheus_components): 'prometheus_components' is undefined

    The error appears to be in '/home/user/.ansible/roles/buluma.prometheus/tasks/install-prometheus.yml': line 11, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


        - name: set internal variables for convenience
          ^ here
```

## Environment

Version
```
ansible [core 2.12.2]
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

Server where ansible
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```

Remote server
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```
