### ISSUE TITLE
Can not add custom prometheus_targets

### ISSUE THREAD

**Issue by patsevanton** [buluma/ansible-role-prometheus#6]
## Describe the bug

Can not add custom prometheus_targets

## Playbook

```yaml
- name: Install prometheus and Grafana
  become: true
  hosts: prometheus
  roles:
    - role: cloudalchemy.node_exporter
    - role: buluma.prometheus
    - role: buluma.grafana
```

## Inventory
```
all:
  children:
    prometheus:
      hosts:
        "prometheus":
          ansible_host: "xxxxx"
  vars:
    ansible_user:  ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
    prometheus_components: [ "prometheus", "node_exporter" ]
    grafana_version: 7.5.15
    grafana_use_provisioning: true
    grafana_security:
      admin_user: admin
      admin_password: enter_your_secure_password
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false
    grafana_dashboards:
    - dashboard_id: 1860
      revision_id: 26
      datasource: prometheus
```

## cat prometheus.yml
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'master'

# A list of scrape configurations.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout:  10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "node"
    file_sd_configs:
      - files:
        - '/etc/prometheus/tgroups/*.json'
        - '/etc/prometheus/tgroups/*.yml'
        - '/etc/prometheus/tgroups/*.yaml'
    #static_configs:
    #- targets:
    #  - "localhost:9100"
```

## Environment
Version
```
ansible [core 2.12.2]
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

Server where ansible
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```

Remote server
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```
